Repository paritytech/parity-bridges-common, pull requests merged in 2020-08, with the labels that each got.

#243 Bump Substrate to RC5
  Cargo.lock
  bin/node/node/Cargo.toml
  bin/node/node/src/command.rs
  bin/node/node/src/service.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  modules/currency-exchange/Cargo.toml
  modules/currency-exchange/src/lib.rs
  modules/ethereum-contract/builtin/Cargo.toml
  modules/ethereum/Cargo.toml
  modules/ethereum/src/mock.rs
  modules/substrate/Cargo.toml
  modules/substrate/src/lib.rs
  primitives/currency-exchange/Cargo.toml
  primitives/ethereum-poa/Cargo.toml
  relays/ethereum/Cargo.toml
Labels: A-chores, A-deps

#238 Support Pallet Instances in Relay
  relays/ethereum/src/cli.yml
  relays/ethereum/src/ethereum_deploy_contract.rs
  relays/ethereum/src/ethereum_exchange.rs
  relays/ethereum/src/ethereum_exchange_submit.rs
  relays/ethereum/src/ethereum_sync_loop.rs
  relays/ethereum/src/instances.rs
  relays/ethereum/src/main.rs
  relays/ethereum/src/substrate_client.rs
  relays/ethereum/src/substrate_sync_loop.rs
  relays/ethereum/src/sync.rs
Labels: P-Relay

#264 Fix vars substitution on update.
  deployments/rialto/update.sh
Labels: P-Devops

#253 Prepare for sub to eth relay - part2
  relays/ethereum/res/substrate-bridge-abi.json
  relays/ethereum/res/substrate-bridge-bytecode.hex
  relays/ethereum/res/substrate-bridge-metadata.txt
  relays/ethereum/src/ethereum_client.rs
  relays/ethereum/src/exchange_loop.rs
  relays/ethereum/src/rpc_errors.rs
  relays/ethereum/src/substrate_client.rs
  relays/ethereum/src/sync.rs
  relays/ethereum/src/sync_loop.rs
Labels: B-Substrate to PoA, P-Relay

#254 Substrate -> PoA relay in docker environment
  deployments/rialto/docker-compose.yml
Labels: B-Substrate to PoA

#268 Fix OpenEthereum Docker Builds
  deployments/rialto/OpenEthereum.Dockerfile
Labels: P-Devops

#267 Publish Bridge Node and Relay Docker Images
  .github/workflows/publish-docker.yml
  .github/workflows/rust.yml
Labels: A-feat, P-Devops

#271 Rename Primitive Crates
  Cargo.lock
  bin/node/node/Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/exchange.rs
  bin/node/runtime/src/kovan.rs
  bin/node/runtime/src/lib.rs
  bin/node/runtime/src/rialto.rs
  modules/currency-exchange/Cargo.toml
  modules/currency-exchange/src/lib.rs
  modules/ethereum/Cargo.toml
  modules/ethereum/src/benchmarking.rs
  modules/ethereum/src/finality.rs
  modules/ethereum/src/import.rs
  modules/ethereum/src/lib.rs
  modules/ethereum/src/mock.rs
  modules/ethereum/src/test_utils.rs
  modules/ethereum/src/validators.rs
  modules/ethereum/src/verification.rs
  primitives/currency-exchange/Cargo.toml
  primitives/ethereum-poa/Cargo.toml
  relays/ethereum/Cargo.toml
  relays/ethereum/src/ethereum_exchange.rs
  relays/ethereum/src/ethereum_exchange_submit.rs
  relays/ethereum/src/rpc.rs
  relays/ethereum/src/substrate_client.rs
  relays/ethereum/src/substrate_types.rs
Labels: PR-Merge at will when CI green, dependencies

#275 Fix panic when no `instance` is passed to certain CLI options
  relays/ethereum/src/cli.yml
Labels: A-bug

#273 Use different hashes to avoid unnecessary rebuilds.
  deployments/rialto/docker-compose.yml
  deployments/rialto/update.sh
Labels: P-Devops

#280 Add instructions and scripts for local development
  README.md
  deployments/dev/poa-config/keys/BridgePoa/address_book.json
  deployments/dev/poa-config/keys/BridgePoa/arthur.json
  deployments/dev/poa-config/pass
  deployments/dev/poa-config/poa-node-config
  deployments/dev/poa-config/poa.json
  scripts/run-bridge-node.sh
  scripts/run-eth2sub-relay.sh
  scripts/run-openethereum-node.sh
Labels: A-docs

#288 Update jsonrpsee reference
  Cargo.lock
  deployments/rialto/dashboard/grafana/provisioning/dashboards/relay-eth2sub-sync-dashboard.json
  deployments/rialto/dashboard/grafana/provisioning/dashboards/relay-sub2eth-sync-dashboard.json
Labels: P-Relay

#290 Update open ethereum.
  README.md
  deployments/rialto/OpenEthereum.Dockerfile
  deployments/rialto/docker-compose.yml
Labels: PR-Merge at will when CI green

#289 Parse all deploy contract arguments
  relays/ethereum/src/main.rs
Labels: P-Relay

#287 Introduce Minimal Header Chain: Proving Interface
  Cargo.lock
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/kovan.rs
  bin/node/runtime/src/rialto.rs
  modules/currency-exchange/Cargo.toml
  modules/currency-exchange/src/benchmarking.rs
  modules/currency-exchange/src/lib.rs
  primitives/header-chain/Cargo.toml
  primitives/header-chain/src/lib.rs
Labels: P-Runtime

#292 Remove old Substrate pallet
  Cargo.lock
  modules/substrate/Cargo.toml
  modules/substrate/src/lib.rs
Labels: B-Substrate to Substrate

#293 Changed MAX_SUBMITTED_HEADERS to 4 in sub2eth
  relays/ethereum/src/substrate_sync_loop.rs
Labels: P-Relay

#294 Remove errors from log
  bin/node/runtime/src/exchange.rs
  relays/ethereum/src/headers.rs
  relays/ethereum/src/sync_loop.rs
Labels: P-Relay

#297 Fix (workaround) for "cannot read property 'toFixed' of null"
  relays/ethereum/src/metrics.rs
Labels: P-Relay

#276 Use Images from DockerHub in Rialto Docker-Compose
  .github/workflows/publish-docker.yml
  deployments/README.md
  deployments/rialto/docker-compose.git.yml
  deployments/rialto/docker-compose.yml
  deployments/rialto/update.sh
Labels: PR-Merge at will when CI green

#321 Update substrate reference to rc6
  Cargo.lock
  bin/node/node/Cargo.toml
  bin/node/node/src/command.rs
  bin/node/node/src/service.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/exchange.rs
  bin/node/runtime/src/lib.rs
  modules/currency-exchange/Cargo.toml
  modules/ethereum-contract/builtin/Cargo.toml
  modules/ethereum/Cargo.toml
  modules/substrate/Cargo.toml
  primitives/currency-exchange/Cargo.toml
  primitives/ethereum-poa/Cargo.toml
  relays/ethereum/Cargo.toml
Labels: dependencies

#322 Unpin Nightly Rust
  .github/workflows/rust.yml
Labels: PR-Merge at will when CI green

#299 Initial version of DummyOrdered pallet
  Cargo.lock
  bin/node/runtime/Cargo.toml
  modules/message-lane/Cargo.toml
  modules/message-lane/src/inbound_lane.rs
  modules/message-lane/src/lib.rs
  modules/message-lane/src/mock.rs
  modules/message-lane/src/outbound_lane.rs
  primitives/message-lane/Cargo.toml
  primitives/message-lane/src/lib.rs
Labels: B-Substrate to Substrate, P-Message Delivery, PR-Merge at will when CI green

#331 Whitelist extensions in CORS settings for PoA nodes
  deployments/dev/poa-config/poa-node-config
  deployments/rialto/poa-config/poa-node-config
Labels: A-feat, P-Devops, PR-Merge at will when CI green
