Repository paritytech/parity-bridges-common, pull requests merged in 2020-07, with the labels that each got.

#157 Create accounts from DepositInto::deposit_into()
  bin/node/runtime/src/lib.rs
  modules/currency-exchange/src/lib.rs
  primitives/currency-exchange/src/lib.rs
Labels: PoA to Substrate

#159 Revert "Rollback Rust nightly version (#109)"
  .travis.yml
Labels: merge at will when ci green

#155 Sign PoA transactions from wasm env
  Cargo.lock
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/exchange.rs
  primitives/ethereum-poa/src/lib.rs
  primitives/ethereum-poa/src/signatures.rs
Labels: PoA to Substrate

#172 Fix sub2eth synchronization
  relays/ethereum/Cargo.toml
  relays/ethereum/res/substrate-bridge-abi.json
  relays/ethereum/res/substrate-bridge-bytecode.hex
  relays/ethereum/res/substrate-bridge-metadata.txt
  relays/ethereum/src/ethereum_client.rs
  relays/ethereum/src/ethereum_sync_loop.rs
  relays/ethereum/src/headers.rs
  relays/ethereum/src/substrate_client.rs
  relays/ethereum/src/substrate_sync_loop.rs
  relays/ethereum/src/sync.rs
  relays/ethereum/src/sync_loop.rs
  relays/ethereum/src/sync_types.rs
Labels: Substrate to PoA

#178 Backoff on connection-unrelated errors
  Cargo.lock
  relays/ethereum/Cargo.toml
  relays/ethereum/src/sync_loop.rs
Labels: PoA to Substrate, Substrate to PoA, merge at will when ci green

#175 Update Substrate to rc4
  Cargo.lock
  bin/node/node/Cargo.toml
  bin/node/node/src/service.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  modules/currency-exchange/Cargo.toml
  modules/currency-exchange/src/lib.rs
  modules/ethereum-contract/builtin/Cargo.toml
  modules/ethereum/Cargo.toml
  modules/ethereum/src/mock.rs
  modules/substrate/Cargo.toml
  modules/substrate/src/lib.rs
  primitives/currency-exchange/Cargo.toml
  primitives/ethereum-poa/Cargo.toml
  relays/ethereum/Cargo.toml
  relays/substrate/Cargo.toml
  scripts/update_rc.sh
Labels: dependencies, merge at will when ci green

#180 Do not panic (in backoff tests) when logging is enabled
  relays/ethereum/src/sync_loop.rs
Labels: merge at will when ci green

#182 Basic tests for sync loop
  relays/ethereum/src/ethereum_sync_loop.rs
  relays/ethereum/src/main.rs
  relays/ethereum/src/substrate_sync_loop.rs
  relays/ethereum/src/sync.rs
  relays/ethereum/src/sync_loop.rs
  relays/ethereum/src/sync_loop_tests.rs
Labels: PoA to Substrate, Substrate to PoA

#177 Relay PoA lock-funds transactions proofs
  Cargo.lock
  README.md
  bin/node/runtime/src/lib.rs
  modules/currency-exchange/src/lib.rs
  modules/ethereum/src/lib.rs
  primitives/currency-exchange/src/lib.rs
  primitives/ethereum-poa/src/lib.rs
  relays/ethereum/Cargo.toml
  relays/ethereum/src/cli.yml
  relays/ethereum/src/ethereum_client.rs
  relays/ethereum/src/ethereum_exchange.rs
  relays/ethereum/src/ethereum_types.rs
  relays/ethereum/src/exchange.rs
  relays/ethereum/src/main.rs
  relays/ethereum/src/rpc.rs
  relays/ethereum/src/rpc_errors.rs
  relays/ethereum/src/substrate_client.rs
Labels: PoA to Substrate, merge at will when ci green

#188 Fixed best_ethereum_block() call parameters encoding
  Cargo.lock
  bin/node/runtime/Cargo.toml
  modules/currency-exchange/Cargo.toml
  modules/ethereum-contract/builtin/Cargo.toml
  modules/ethereum/Cargo.toml
  modules/substrate/Cargo.toml
  primitives/currency-exchange/Cargo.toml
  primitives/ethereum-poa/Cargo.toml
  relays/ethereum/Cargo.toml
  relays/ethereum/src/substrate_client.rs
Labels: PoA to Substrate

#158 Exchange pallet benchmarks
  Cargo.lock
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/exchange.rs
  bin/node/runtime/src/lib.rs
  modules/currency-exchange/src/benchmarking.rs
  modules/currency-exchange/src/lib.rs
  modules/ethereum/src/benchmarking.rs
  modules/ethereum/src/lib.rs
  modules/ethereum/src/test_utils.rs
  primitives/ethereum-poa/Cargo.toml
  primitives/ethereum-poa/src/lib.rs
Labels: PoA to Substrate

#191 Relay dashboard
  Cargo.lock
  relays/ethereum/Cargo.toml
  relays/ethereum/dashboard/grafana-dashboard.json
  relays/ethereum/dashboard/grafana-dashboard.yaml
  relays/ethereum/dashboard/grafana-datasource.yaml
  relays/ethereum/dashboard/prometheus.yml
  relays/ethereum/src/cli.yml
  relays/ethereum/src/ethereum_sync_loop.rs
  relays/ethereum/src/main.rs
  relays/ethereum/src/metrics.rs
  relays/ethereum/src/substrate_sync_loop.rs
  relays/ethereum/src/sync.rs
  relays/ethereum/src/sync_loop.rs
  relays/ethereum/src/sync_loop_metrics.rs
  relays/ethereum/src/sync_loop_tests.rs
  relays/ethereum/src/sync_types.rs
Labels: B-PoA to Substrate, B-Substrate to PoA

#221 Add Prometheus and Grafana to Docker Compose
  README.md
  deployments/README.md
  deployments/dashboard/grafana/provisioning/dashboards/grafana-dashboard.json
  deployments/dashboard/grafana/provisioning/dashboards/grafana-dashboard.yaml
  deployments/dashboard/grafana/provisioning/datasources/grafana-datasource.yaml
  deployments/dashboard/prometheus/prometheus.yml
  deployments/rialto/bridge-config/relay-eth2sub-entrypoint.sh
  deployments/rialto/docker-compose.yml
  relays/ethereum/dashboard/grafana-datasource.yaml
Labels: P-Devops

#228 Relay healthcheck
  .github/workflows/rust.yml
  Dockerfile
  deployments/rialto/Bridge.Dockerfile
  deployments/rialto/docker-compose.yml
Labels: P-Relay

#230 Faster re-build of docker images.
  .gitignore
  deployments/rialto/Bridge.Dockerfile
  deployments/rialto/OpenEthereum.Dockerfile
  deployments/rialto/docker-compose.yml
  deployments/rialto/update.sh
Labels: P-Devops

#227 Auto relay exchange transactions
  Cargo.lock
  bin/node/runtime/src/lib.rs
  deployments/rialto/bridge-config/relay-eth-exchange-sub-entrypoint.sh
  deployments/rialto/docker-compose.yml
  modules/currency-exchange/src/lib.rs
  primitives/currency-exchange/Cargo.toml
  primitives/currency-exchange/src/lib.rs
  relays/ethereum/Cargo.toml
  relays/ethereum/src/cli.yml
  relays/ethereum/src/ethereum_client.rs
  relays/ethereum/src/ethereum_exchange.rs
  relays/ethereum/src/exchange.rs
  relays/ethereum/src/exchange_loop.rs
  relays/ethereum/src/main.rs
  relays/ethereum/src/rpc.rs
  relays/ethereum/src/rpc_errors.rs
  relays/ethereum/src/substrate_client.rs
  relays/ethereum/src/sync_loop.rs
  relays/ethereum/src/sync_loop_tests.rs
  relays/ethereum/src/utils.rs
Labels: B-PoA to Substrate, P-Relay

#226 Allow Multiple Bridge Pallet Instances
  .github/workflows/rust.yml
  bin/node/node/Cargo.toml
  bin/node/node/src/chain_spec.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/exchange.rs
  bin/node/runtime/src/kovan.rs
  bin/node/runtime/src/lib.rs
  bin/node/runtime/src/rialto.rs
  modules/currency-exchange/src/benchmarking.rs
  modules/currency-exchange/src/lib.rs
  modules/ethereum/src/benchmarking.rs
  modules/ethereum/src/import.rs
  modules/ethereum/src/lib.rs
  modules/ethereum/src/mock.rs
  modules/ethereum/src/test_utils.rs
  modules/ethereum/src/validators.rs
  modules/ethereum/src/verification.rs
  primitives/currency-exchange/src/lib.rs
  primitives/ethereum-poa/src/lib.rs
  relays/ethereum/src/substrate_client.rs
Labels: B-PoA to Substrate, B-Substrate to PoA, P-Runtime

#233 Fix Local Dockerfile Entrypoint
  Dockerfile
  README.md
  deployments/rialto/Bridge.Dockerfile
  deployments/scripts/bridge-entrypoint.sh
Labels: P-Devops

#236 Make transactions receipts part of transaction inclusion proof
  bin/node/runtime/src/exchange.rs
  bin/node/runtime/src/kovan.rs
  bin/node/runtime/src/lib.rs
  bin/node/runtime/src/rialto.rs
  modules/ethereum/src/lib.rs
  modules/ethereum/src/test_utils.rs
  primitives/ethereum-poa/src/lib.rs
  primitives/ethereum-poa/src/signatures.rs
  relays/ethereum/src/ethereum_exchange.rs
  relays/ethereum/src/substrate_types.rs
Labels: B-PoA to Substrate, P-Relay, PR-Merge at will when CI green

#237 Auto exchange transactions relay metrics
  Cargo.lock
  deployments/rialto/dashboard/prometheus/prometheus.yml
  relays/ethereum/src/cli.yml
  relays/ethereum/src/ethereum_exchange.rs
  relays/ethereum/src/exchange.rs
  relays/ethereum/src/exchange_loop.rs
  relays/ethereum/src/exchange_loop_metrics.rs
  relays/ethereum/src/main.rs
  relays/ethereum/src/metrics.rs
  relays/ethereum/src/sync_loop.rs
  relays/ethereum/src/sync_loop_metrics.rs
Labels: B-PoA to Substrate, P-Relay, PR-Merge at will when CI green

#239 Fixed stringified method name
  relays/ethereum/src/substrate_client.rs
Labels: P-Relay, PR-Merge at will when CI green

#244 Remove substrate relay code
  Cargo.lock
  Cargo.toml
  relays/substrate/Cargo.toml
  relays/substrate/README.md
  relays/substrate/src/bridge.rs
  relays/substrate/src/error.rs
  relays/substrate/src/main.rs
  relays/substrate/src/params.rs
  relays/substrate/src/rpc.rs
Labels: PR-Merge at will when CI green

#250 Pin nightly to fix clippy.
  .github/workflows/rust.yml
Labels: P-Devops

#247 Remove substrate-bridge artifact.
  .github/workflows/rust.yml
Labels: P-Devops

#229 Submit exchange transactions to PoA node
  Cargo.lock
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/exchange.rs
  deployments/rialto/bridge-config/poa-exchange-tx-generator-entrypoint.sh
  deployments/rialto/docker-compose.yml
  modules/ethereum/Cargo.toml
  primitives/ethereum-poa/Cargo.toml
  primitives/ethereum-poa/src/lib.rs
  relays/ethereum/Cargo.toml
  relays/ethereum/src/cli.yml
  relays/ethereum/src/ethereum_exchange_submit.rs
  relays/ethereum/src/main.rs
Labels: B-PoA to Substrate, P-Relay

#249 Don't start proxy by default.
  deployments/rialto/update.sh
Labels: P-Devops

#251 Add server domain to grafana.
  deployments/rialto/dashboard/grafana/provisioning/dashboards/relay-eth2sub-sync-dashboard.json
  deployments/rialto/docker-compose.yml
Labels: P-Devops

#252 Expose metrics port for exchange-tx relay.
  deployments/rialto/bridge-config/relay-eth-exchange-sub-entrypoint.sh
  deployments/rialto/docker-compose.yml
Labels: P-Devops

#256 Fix env issues.
  .gitignore
  deployments/rialto/update.sh
Labels: P-Devops

#259 Update no new blocks alert in eth2sub dashboard
  deployments/rialto/dashboard/grafana/provisioning/dashboards/relay-eth2sub-sync-dashboard.json
Labels: B-PoA to Substrate, P-Devops

#248 Prepare for sub to eth relay
  bin/node/runtime/src/rialto.rs
  deployments/rialto/poa-config/poa.json
  relays/ethereum/src/ethereum_client.rs
  relays/ethereum/src/ethereum_deploy_contract.rs
  relays/ethereum/src/exchange.rs
  relays/ethereum/src/rpc_errors.rs
  relays/ethereum/src/substrate_client.rs
  relays/ethereum/src/substrate_sync_loop.rs
  relays/ethereum/src/sync_loop.rs
  relays/ethereum/src/sync_loop_tests.rs
  relays/ethereum/src/sync_types.rs
  relays/ethereum/src/utils.rs
Labels: B-Substrate to PoA, P-Relay

#260 Fix generator in case tty is not available.
  deployments/rialto/bridge-config/poa-exchange-tx-generator-entrypoint.sh
Labels: P-Devops

#258 Add traces to PoA builtin
  Cargo.lock
  deployments/rialto/OpenEthereum.Dockerfile
  deployments/rialto/docker-compose.yml
  modules/ethereum-contract/builtin/Cargo.toml
  modules/ethereum-contract/builtin/src/lib.rs
Labels: B-Substrate to PoA

#261 Fix gas_used fields in receipts
  modules/currency-exchange/src/lib.rs
  modules/ethereum/src/lib.rs
  modules/ethereum/src/validators.rs
  modules/ethereum/src/verification.rs
  primitives/ethereum-poa/src/lib.rs
  relays/ethereum/src/ethereum_client.rs
  relays/ethereum/src/ethereum_types.rs
  relays/ethereum/src/rpc_errors.rs
  relays/ethereum/src/substrate_types.rs
Labels: B-PoA to Substrate
