Repository paritytech/parity-bridges-common, pull requests merged in 2020-06, with the labels that each got.

#119 Downgrade async-std to 1.5.0
  Cargo.lock
  relays/ethereum/Cargo.toml
  relays/substrate/Cargo.toml
Labels: Substrate to PoA, Substrate to Substrate

#105 Limit number of headers that are pruned within single import Call
  modules/ethereum/src/import.rs
  modules/ethereum/src/lib.rs
Labels: merge at will when ci green

#121 Provide overview about project components
  README.md
Labels: documentation

#122 Add diagrams from draw.io
  diagrams/ARCHITECTURE.md
  diagrams/bridge-architecture-diagrams.drawio
  diagrams/bridge-relay.svg
  diagrams/cross-chain-fund-transfer.svg
  diagrams/currency-exchange-pallet.svg
  diagrams/ethereum-pallet.svg
  diagrams/general-overview.svg
  diagrams/parachain.svg
Labels: documentation

#123 Add async_trait to SourceClient and TargetClient
  relays/ethereum/src/ethereum_client.rs
  relays/ethereum/src/ethereum_sync_loop.rs
  relays/ethereum/src/substrate_client.rs
  relays/ethereum/src/substrate_sync_loop.rs
  relays/ethereum/src/sync_loop.rs
  relays/ethereum/src/sync_types.rs
Labels: merge at will when ci green

#131 Switch to new RPC interface
  Cargo.lock
  relays/ethereum/Cargo.toml
  relays/ethereum/src/ethereum_client.rs
  relays/ethereum/src/ethereum_deploy_contract.rs
  relays/ethereum/src/ethereum_sync_loop.rs
  relays/ethereum/src/main.rs
  relays/ethereum/src/rpc.rs
  relays/ethereum/src/rpc_errors.rs
  relays/ethereum/src/substrate_client.rs
  relays/ethereum/src/substrate_sync_loop.rs
  relays/ethereum/src/sync.rs
  relays/ethereum/src/sync_loop.rs
Labels: merge at will when ci green
