Repository paritytech/parity-bridges-common, pull requests merged in 2021-05, with the labels that each got.

#948 Move pallet-bridge-dispatch types to primitives
  Cargo.lock
  bin/rialto/runtime/src/lib.rs
  bin/runtime-common/README.md
  bin/runtime-common/src/messages.rs
  docs/high-level-overview.md
  modules/dispatch/README.md
  modules/dispatch/src/lib.rs
  primitives/message-dispatch/Cargo.toml
  primitives/message-dispatch/src/lib.rs
  relays/bin-substrate/Cargo.toml
  relays/bin-substrate/src/chains/millau.rs
  relays/bin-substrate/src/chains/mod.rs
  relays/bin-substrate/src/chains/rialto.rs
  relays/bin-substrate/src/cli/send_message.rs
Labels: P-Message Dispatch

#955 Bump Substrate to `ec180313`
  Cargo.lock
  bin/millau/node/Cargo.toml
  bin/millau/node/src/service.rs
  bin/rialto/node/Cargo.toml
  bin/rialto/node/src/service.rs
Labels: A-chores, dependencies

#947 Bump Substrate WASM builder
  Cargo.lock
  bin/millau/node/src/chain_spec.rs
  bin/millau/runtime/Cargo.toml
  bin/millau/runtime/build.rs
  bin/rialto/node/src/chain_spec.rs
  bin/rialto/runtime/Cargo.toml
  bin/rialto/runtime/build.rs
Labels: dependencies

#957 Bump endowment amounts on Rialto and Millau
  bin/millau/node/src/chain_spec.rs
  bin/rialto/node/src/chain_spec.rs
Labels: B-Substrate <> Substrate

#958 Bump Substrate to `b094edaf`
  Cargo.lock
  bin/millau/node/src/cli.rs
  bin/millau/runtime/src/lib.rs
  bin/rialto/node/src/cli.rs
  bin/rialto/runtime/src/lib.rs
Labels: dependencies

#961 Upstream changes from Polkadot repo
  deployments/local-scripts/relay-headers-rococo-to-wococo.sh
  deployments/local-scripts/relay-headers-wococo-to-rococo.sh
  deployments/local-scripts/run-rococo-bob-node.sh
  deployments/local-scripts/run-rococo-node.sh
  deployments/local-scripts/run-wococo-node.sh
  primitives/chain-rococo/src/lib.rs
  primitives/chain-wococo/src/lib.rs
Labels: B-Substrate <> Substrate

#963 Pass source and target chain ids to account_ownership_digest
  bin/millau/node/src/chain_spec.rs
  bin/millau/runtime/src/lib.rs
  bin/millau/runtime/src/rialto_messages.rs
  bin/rialto/node/src/chain_spec.rs
  bin/rialto/runtime/src/lib.rs
  bin/rialto/runtime/src/millau_messages.rs
  bin/runtime-common/src/messages.rs
  deployments/types-millau.json
  deployments/types-rialto.json
  deployments/types/common.json
  modules/dispatch/src/lib.rs
  primitives/chain-kusama/src/lib.rs
  primitives/chain-millau/src/lib.rs
  primitives/chain-polkadot/src/lib.rs
  primitives/chain-rialto/src/lib.rs
  primitives/chain-westend/src/lib.rs
  primitives/chain-wococo/src/lib.rs
  primitives/message-dispatch/src/lib.rs
  primitives/runtime/src/lib.rs
  relays/bin-substrate/src/chains/millau_messages_to_rialto.rs
  relays/bin-substrate/src/chains/mod.rs
  relays/bin-substrate/src/chains/rialto_messages_to_millau.rs
  relays/bin-substrate/src/cli/bridge.rs
  relays/bin-substrate/src/messages_source.rs
  relays/bin-substrate/src/messages_target.rs
Labels: B-Substrate <> Substrate

#965 Start finality relay spec-version guards for Rococo <> Wococo finality relays
  relays/bin-substrate/src/chains/rococo_headers_to_wococo.rs
  relays/bin-substrate/src/chains/wococo_headers_to_rococo.rs
  relays/bin-substrate/src/cli/relay_headers.rs
  relays/bin-substrate/src/finality_pipeline.rs
Labels: B-Substrate <> Substrate, P-Relay

#964 Serve multiple lanes with single complex relay instance
  relays/bin-substrate/src/cli/relay_headers_and_messages.rs
Labels: B-Substrate <> Substrate, P-Message Delivery, P-Relay

#971 Relays loops are trying to connect to their nodes until connection is successfully established
  Cargo.lock
  relays/bin-ethereum/src/ethereum_deploy_contract.rs
  relays/bin-ethereum/src/ethereum_exchange.rs
  relays/bin-ethereum/src/ethereum_exchange_submit.rs
  relays/bin-ethereum/src/ethereum_sync_loop.rs
  relays/bin-ethereum/src/substrate_sync_loop.rs
  relays/bin-substrate/src/cli/mod.rs
  relays/client-ethereum/Cargo.toml
  relays/client-ethereum/src/client.rs
  relays/client-substrate/src/client.rs
Labels: P-Relay

#972 Bump `environmental` dependency
  Cargo.lock
Labels: dependencies

#973 Avoid hashing headers twice in verify_justification
  primitives/header-chain/src/justification.rs
Labels: B-Substrate <> Substrate, P-Runtime

#974 Increase pause before starting relays
  deployments/bridges/poa-rialto/entrypoints/relay-headers-poa-to-rialto-entrypoint.sh
  deployments/bridges/poa-rialto/entrypoints/relay-poa-exchange-rialto-entrypoint.sh
  deployments/bridges/rialto-millau/entrypoints/relay-messages-millau-to-rialto-entrypoint.sh
  deployments/bridges/rialto-millau/entrypoints/relay-messages-rialto-to-millau-entrypoint.sh
  deployments/bridges/rialto-millau/entrypoints/relay-millau-rialto-entrypoint.sh
  deployments/bridges/westend-millau/entrypoints/relay-headers-westend-to-millau-entrypoint.sh
Labels: A-chores

#976 Bump Rococo/Wococo spec_version
  primitives/chain-rococo/src/lib.rs
  primitives/chain-wococo/src/lib.rs
Labels: B-Substrate <> Substrate

#980 Update cargo.deny
  Cargo.lock
  deny.toml
Labels: A-chores

#977 Add JSON type definitions for Rococo<>Wococo bridge
  deployments/types-rococo.json
  deployments/types-wococo.json
  deployments/types/build.sh
  deployments/types/common.json
  deployments/types/millau.json
  deployments/types/rialto-millau.json
  deployments/types/rococo-wococo.json
  deployments/types/rococo.json
  deployments/types/wococo.json
Labels: B-Substrate <> Substrate, P-User Interface

#975 Always run on-demand headers relay in complex relay
  Cargo.lock
  relays/bin-substrate/src/cli/relay_headers.rs
  relays/bin-substrate/src/finality_pipeline.rs
  relays/bin-substrate/src/messages_source.rs
  relays/bin-substrate/src/messages_target.rs
  relays/bin-substrate/src/on_demand_headers.rs
  relays/client-substrate/Cargo.toml
  relays/client-substrate/src/finality_source.rs
  relays/finality/src/finality_loop.rs
  relays/finality/src/finality_loop_tests.rs
  relays/utils/src/relay_loop.rs
Labels: B-Substrate <> Substrate, P-Relay

#979 Custom justification verification
  Cargo.lock
  primitives/header-chain/Cargo.toml
  primitives/header-chain/src/justification.rs
  primitives/header-chain/tests/implementation_match.rs
  primitives/header-chain/tests/justification.rs
  primitives/test-utils/src/lib.rs
Labels: B-Substrate <> Substrate, P-Runtime, PR-needsaudit
