Repository paritytech/parity-bridges-common, pull requests merged in 2021-09, with the labels that each got.

#1088 [BREAKING] Migrate messages pallet to frame v2
  bin/millau/node/src/chain_spec.rs
  bin/millau/runtime/src/lib.rs
  bin/millau/runtime/src/rialto_messages.rs
  bin/rialto/node/src/chain_spec.rs
  bin/rialto/runtime/src/lib.rs
  bin/rialto/runtime/src/millau_messages.rs
  bin/runtime-common/src/messages.rs
  bin/runtime-common/src/messages_api.rs
  modules/messages/src/benchmarking.rs
  modules/messages/src/inbound_lane.rs
  modules/messages/src/lib.rs
  primitives/chain-millau/src/lib.rs
  primitives/chain-rialto/src/lib.rs
  primitives/chain-rococo/src/lib.rs
  primitives/chain-wococo/src/lib.rs
  relays/bin-substrate/src/chains/millau_messages_to_rialto.rs
  relays/bin-substrate/src/chains/rialto_messages_to_millau.rs
  relays/bin-substrate/src/chains/rococo_messages_to_wococo.rs
  relays/bin-substrate/src/chains/wococo_messages_to_rococo.rs
  relays/client-rococo/src/runtime.rs
  relays/client-wococo/src/runtime.rs
  relays/lib-substrate-relay/src/messages_lane.rs
  relays/lib-substrate-relay/src/messages_source.rs
  relays/lib-substrate-relay/src/messages_target.rs
Labels: A-chores, PR-breaksrelay, PR-breaksruntime

#1005 Stored conversion rate updater
  bin/millau/node/src/chain_spec.rs
  bin/millau/runtime/src/lib.rs
  bin/rialto/node/src/chain_spec.rs
  bin/rialto/runtime/src/lib.rs
  deployments/README.md
  deployments/bridges/rialto-millau/entrypoints/relay-messages-to-millau-generator-entrypoint.sh
  deployments/bridges/rialto-millau/entrypoints/relay-messages-to-rialto-generator-entrypoint.sh
  deployments/bridges/rialto-millau/entrypoints/relay-millau-rialto-entrypoint.sh
  relays/bin-substrate/src/chains/millau_messages_to_rialto.rs
  relays/bin-substrate/src/chains/mod.rs
  relays/bin-substrate/src/chains/rialto_messages_to_millau.rs
  relays/bin-substrate/src/cli/mod.rs
  relays/bin-substrate/src/cli/relay_headers_and_messages.rs
  relays/client-substrate/src/metrics/float_storage_value.rs
  relays/lib-substrate-relay/src/conversion_rate_update.rs
  relays/lib-substrate-relay/src/lib.rs
  relays/lib-substrate-relay/src/messages_lane.rs
Labels: B-Substrate <> Substrate, P-Relay, P-Message Delivery

#1107 Fix master compilation
  relays/bin-substrate/src/chains/millau_messages_to_rialto.rs
  relays/bin-substrate/src/chains/rialto_messages_to_millau.rs
Labels: A-chores

#1110 Fix spellcheck
  .config/lingua.dic
  modules/ethereum/src/import.rs
  modules/grandpa/src/benchmarking.rs
  primitives/token-swap/src/lib.rs
  relays/bin-ethereum/src/rpc_errors.rs
  relays/headers/src/sync_types.rs
Labels: A-chores

#1109 Fix delivery transaction estimation used by rational relayer
  Cargo.lock
  bin/millau/runtime/src/lib.rs
  bin/rialto/runtime/src/lib.rs
  primitives/chain-kusama/Cargo.toml
  primitives/chain-kusama/src/lib.rs
  primitives/chain-millau/src/lib.rs
  primitives/chain-polkadot/Cargo.toml
  primitives/chain-polkadot/src/lib.rs
  primitives/chain-rialto/src/lib.rs
  primitives/chain-rococo/src/lib.rs
  primitives/chain-westend/Cargo.toml
  primitives/chain-westend/src/lib.rs
  primitives/chain-wococo/src/lib.rs
  relays/bin-substrate/src/chains/millau_messages_to_rialto.rs
  relays/bin-substrate/src/chains/rialto_messages_to_millau.rs
  relays/bin-substrate/src/chains/rococo_messages_to_wococo.rs
  relays/bin-substrate/src/chains/wococo_messages_to_rococo.rs
  relays/bin-substrate/src/cli/send_message.rs
  relays/client-kusama/src/lib.rs
  relays/client-millau/src/lib.rs
  relays/client-polkadot/src/lib.rs
  relays/client-rialto/src/lib.rs
  relays/client-rococo/src/lib.rs
  relays/client-substrate/src/chain.rs
  relays/client-substrate/src/client.rs
  relays/client-substrate/src/guard.rs
  relays/client-substrate/src/lib.rs
  relays/client-westend/src/lib.rs
  relays/client-wococo/src/lib.rs
  relays/lib-substrate-relay/Cargo.toml
  relays/lib-substrate-relay/src/messages_lane.rs
  relays/lib-substrate-relay/src/messages_source.rs
  relays/lib-substrate-relay/src/messages_target.rs
  relays/lib-substrate-relay/src/on_demand_headers.rs
  relays/messages/src/message_lane_loop.rs
  relays/messages/src/message_race_delivery.rs
Labels: B-Substrate <> Substrate, P-Relay, P-Message Delivery

#1114 Added missing constants to Kusama/Polkadot primitives
  primitives/chain-kusama/src/lib.rs
  primitives/chain-polkadot/src/lib.rs
  primitives/polkadot-core/src/lib.rs
Labels: B-Substrate <> Substrate

#1118 Fix spelling
  .config/lingua.dic
  modules/messages/src/inbound_lane.rs
  modules/messages/src/lib.rs
  primitives/chain-westend/src/lib.rs
  relays/client-rococo/src/runtime.rs
  relays/client-wococo/src/runtime.rs
  relays/finality/src/finality_loop.rs
  relays/lib-substrate-relay/src/conversion_rate_update.rs
Labels: A-chores

#1119 Fix spelling
  .config/lingua.dic
  modules/ethereum/src/lib.rs
  primitives/messages/src/source_chain.rs
Labels: A-chores

#1120 Fix buildah logout issue:containers/buildah#3500
  .gitlab-ci.yml
Labels: A-bug

#1117 Log max balance drop when sending message
  relays/bin-substrate/src/cli/send_message.rs
Labels: B-Substrate <> Substrate, P-Relay, P-Message Delivery

#1083 Transactions resubmitter
  Cargo.lock
  deployments/bridges/rialto-millau/docker-compose.yml
  deployments/bridges/rialto-millau/entrypoints/relay-messages-to-rialto-resubmitter-entrypoint.sh
  primitives/polkadot-core/src/lib.rs
  relays/bin-ethereum/src/rialto_client.rs
  relays/bin-substrate/Cargo.toml
  relays/bin-substrate/src/chains/millau_headers_to_rialto.rs
  relays/bin-substrate/src/chains/millau_messages_to_rialto.rs
  relays/bin-substrate/src/chains/mod.rs
  relays/bin-substrate/src/chains/rialto_headers_to_millau.rs
  relays/bin-substrate/src/chains/rialto_messages_to_millau.rs
  relays/bin-substrate/src/chains/rococo_headers_to_wococo.rs
  relays/bin-substrate/src/chains/rococo_messages_to_wococo.rs
  relays/bin-substrate/src/chains/westend_headers_to_millau.rs
  relays/bin-substrate/src/chains/wococo_headers_to_rococo.rs
  relays/bin-substrate/src/chains/wococo_messages_to_rococo.rs
  relays/bin-substrate/src/cli/init_bridge.rs
  relays/bin-substrate/src/cli/mod.rs
  relays/bin-substrate/src/cli/resubmit_transactions.rs
  relays/bin-substrate/src/cli/send_message.rs
  relays/client-millau/src/lib.rs
  relays/client-rialto/src/lib.rs
  relays/client-rococo/src/lib.rs
  relays/client-substrate/src/chain.rs
  relays/client-substrate/src/client.rs
  relays/client-substrate/src/error.rs
  relays/client-substrate/src/lib.rs
  relays/client-substrate/src/rpc.rs
  relays/client-westend/src/lib.rs
  relays/client-wococo/src/lib.rs
  relays/utils/src/relay_loop.rs
Labels: B-Substrate <> Substrate, P-Relay

#1087 Move some associated types from relay_substrate_client::Chain to bp_runtime::Chain
  bin/millau/runtime/src/lib.rs
  bin/rialto/runtime/src/lib.rs
  modules/grandpa/src/mock.rs
  modules/token-swap/src/lib.rs
  modules/token-swap/src/mock.rs
  primitives/chain-millau/src/lib.rs
  primitives/chain-rialto/src/lib.rs
  primitives/polkadot-core/src/lib.rs
  primitives/runtime/src/chain.rs
  primitives/runtime/src/lib.rs
  relays/bin-substrate/src/chains/millau_headers_to_rialto.rs
  relays/bin-substrate/src/chains/millau_messages_to_rialto.rs
  relays/bin-substrate/src/chains/rialto_headers_to_millau.rs
  relays/bin-substrate/src/chains/rialto_messages_to_millau.rs
  relays/bin-substrate/src/chains/rococo_headers_to_wococo.rs
  relays/bin-substrate/src/chains/rococo_messages_to_wococo.rs
  relays/bin-substrate/src/chains/westend_headers_to_millau.rs
  relays/bin-substrate/src/chains/wococo_headers_to_rococo.rs
  relays/bin-substrate/src/chains/wococo_messages_to_rococo.rs
  relays/bin-substrate/src/cli/estimate_fee.rs
  relays/bin-substrate/src/cli/send_message.rs
  relays/client-kusama/src/lib.rs
  relays/client-millau/src/lib.rs
  relays/client-polkadot/src/lib.rs
  relays/client-rialto/src/lib.rs
  relays/client-rococo/src/lib.rs
  relays/client-substrate/src/chain.rs
  relays/client-substrate/src/guard.rs
  relays/client-substrate/src/lib.rs
  relays/client-westend/src/lib.rs
  relays/client-wococo/src/lib.rs
  relays/lib-substrate-relay/src/finality_pipeline.rs
  relays/lib-substrate-relay/src/messages_lane.rs
  relays/lib-substrate-relay/src/messages_target.rs
Labels: A-chores, B-Substrate <> Substrate

#1126 Increase pause before messages generation start
  deployments/bridges/rialto-millau/entrypoints/relay-messages-to-millau-generator-entrypoint.sh
  deployments/bridges/rialto-millau/entrypoints/relay-messages-to-rialto-generator-entrypoint.sh
  relays/client-ethereum/src/lib.rs
  relays/client-substrate/src/lib.rs
Labels: A-chores

#1128 Another bunch of words for spellchecker
  .config/lingua.dic
Labels: A-chores

#1127 Set fee for importing mandatory headers to zero
  modules/grandpa/src/lib.rs
Labels: B-Substrate <> Substrate, P-Runtime, PR-needsaudit

#1129 Add --mandatory-headers-only cli option to complex relay
  relays/bin-substrate/src/cli/relay_headers_and_messages.rs
  relays/lib-substrate-relay/src/on_demand_headers.rs
Labels: B-Substrate <> Substrate, P-Relay

#1135 Fix transaction resubmitter limits for Millau -> Rialto transactions
  relays/bin-substrate/src/cli/resubmit_transactions.rs
Labels: B-Substrate <> Substrate, P-Relay

#1053 Add parachain pallets to rialto runtime
  .config/lingua.dic
  Cargo.lock
  bin/rialto/node/Cargo.toml
  bin/rialto/node/src/chain_spec.rs
  bin/rialto/node/src/cli.rs
  bin/rialto/node/src/command.rs
  bin/rialto/node/src/main.rs
  bin/rialto/node/src/overseer.rs
  bin/rialto/node/src/parachains_db.rs
  bin/rialto/node/src/service.rs
  bin/rialto/runtime/Cargo.toml
  bin/rialto/runtime/src/lib.rs
  bin/rialto/runtime/src/parachains.rs
  deny.toml
  primitives/chain-rialto/src/lib.rs
  relays/bin-substrate/src/chains/rialto.rs
  relays/bin-substrate/src/cli/encode_call.rs
  relays/client-rialto/src/lib.rs
Labels: A-chores, B-Substrate <> Substrate

#1137 Increase pause before pinging Rialto nodes
  deployments/bridges/poa-rialto/entrypoints/relay-headers-poa-to-rialto-entrypoint.sh
  deployments/bridges/poa-rialto/entrypoints/relay-headers-rialto-to-poa-entrypoint.sh
  deployments/bridges/poa-rialto/entrypoints/relay-poa-exchange-rialto-entrypoint.sh
  deployments/bridges/rialto-millau/entrypoints/relay-messages-millau-to-rialto-entrypoint.sh
  deployments/bridges/rialto-millau/entrypoints/relay-messages-rialto-to-millau-entrypoint.sh
  deployments/bridges/rialto-millau/entrypoints/relay-millau-rialto-entrypoint.sh
Labels: A-chores

#1099 Integrate token swap pallet into Millau runtime
  Cargo.lock
  bin/millau/runtime/Cargo.toml
  bin/millau/runtime/src/lib.rs
  bin/millau/runtime/src/rialto_messages.rs
  modules/messages/src/lib.rs
  modules/token-swap/Cargo.toml
  modules/token-swap/src/lib.rs
  modules/token-swap/src/mock.rs
  primitives/messages/src/source_chain.rs
  primitives/token-swap/src/lib.rs
  relays/bin-substrate/src/cli/encode_message.rs
  relays/bin-substrate/src/cli/send_message.rs
Labels: B-Substrate <> Substrate

#1141 Relay subcommand that performs token RLT <> MLAU token swap
  Cargo.lock
  bin/millau/node/src/chain_spec.rs
  bin/rialto/node/src/chain_spec.rs
  modules/messages/src/lib.rs
  modules/token-swap/src/lib.rs
  primitives/chain-millau/src/lib.rs
  primitives/runtime/src/lib.rs
  primitives/token-swap/src/lib.rs
  relays/bin-substrate/Cargo.toml
  relays/bin-substrate/src/cli/mod.rs
  relays/bin-substrate/src/cli/swap_tokens.rs
  relays/client-substrate/Cargo.toml
  relays/client-substrate/src/chain.rs
  relays/client-substrate/src/client.rs
  relays/client-substrate/src/lib.rs
  relays/client-substrate/src/metrics/float_storage_value.rs
  relays/client-substrate/src/rpc.rs
Labels: B-Substrate <> Substrate, P-Relay

#1150 Fix spelling
  .config/lingua.dic
  modules/token-swap/src/lib.rs
  relays/bin-substrate/src/cli/swap_tokens.rs
Labels: A-chores

#1154 Box large arguments of GRANDPA pallet
  bin/millau/runtime/src/lib.rs
  bin/rialto/runtime/src/lib.rs
  modules/grandpa/src/benchmarking.rs
  modules/grandpa/src/lib.rs
  primitives/header-chain/src/lib.rs
  relays/bin-substrate/src/chains/kusama_headers_to_polkadot.rs
  relays/bin-substrate/src/chains/millau_headers_to_rialto.rs
  relays/bin-substrate/src/chains/mod.rs
  relays/bin-substrate/src/chains/polkadot_headers_to_kusama.rs
  relays/bin-substrate/src/chains/rialto_headers_to_millau.rs
  relays/bin-substrate/src/chains/rococo_headers_to_wococo.rs
  relays/bin-substrate/src/chains/westend_headers_to_millau.rs
  relays/bin-substrate/src/chains/wococo_headers_to_rococo.rs
  relays/client-kusama/src/runtime.rs
  relays/client-polkadot/src/runtime.rs
  relays/client-rococo/src/runtime.rs
  relays/client-wococo/src/runtime.rs
  relays/lib-substrate-relay/src/headers_initialize.rs
Labels: B-Substrate <> Substrate, PR-breaksrelay, PR-breaksruntime

#1142 Add rialto-parachain runtime and node
  .config/lingua.dic
  .gitlab-ci.yml
  Cargo.lock
  bin/millau/node/Cargo.toml
  bin/millau/node/src/command.rs
  bin/millau/node/src/service.rs
  bin/millau/runtime/Cargo.toml
  bin/millau/runtime/src/lib.rs
  bin/rialto-parachain/node/Cargo.toml
  bin/rialto-parachain/node/build.rs
  bin/rialto-parachain/node/src/chain_spec.rs
  bin/rialto-parachain/node/src/cli.rs
  bin/rialto-parachain/node/src/command.rs
  bin/rialto-parachain/node/src/lib.rs
  bin/rialto-parachain/node/src/main.rs
  bin/rialto-parachain/node/src/service.rs
  bin/rialto-parachain/runtime/Cargo.toml
  bin/rialto-parachain/runtime/build.rs
  bin/rialto-parachain/runtime/src/lib.rs
  bin/rialto/node/Cargo.toml
  bin/rialto/node/src/chain_spec.rs
  bin/rialto/node/src/command.rs
  bin/rialto/node/src/overseer.rs
  bin/rialto/node/src/parachains_db.rs
  bin/rialto/node/src/service.rs
  bin/rialto/runtime/Cargo.toml
  bin/rialto/runtime/src/lib.rs
  bin/rialto/runtime/src/parachains.rs
  modules/currency-exchange/src/lib.rs
  modules/dispatch/src/lib.rs
  modules/ethereum/src/mock.rs
  modules/grandpa/src/mock.rs
  modules/messages/src/mock.rs
  modules/shift-session-manager/src/lib.rs
  modules/token-swap/src/mock.rs
  primitives/chain-millau/Cargo.toml
  primitives/messages/Cargo.toml
  relays/bin-substrate/src/cli/encode_call.rs
  relays/bin-substrate/src/cli/encode_message.rs
  relays/bin-substrate/src/cli/send_message.rs
  relays/client-substrate/Cargo.toml
  relays/client-substrate/src/chain.rs
  relays/client-substrate/src/client.rs
  relays/client-substrate/src/guard.rs
  relays/headers/src/sync.rs
  relays/headers/src/sync_loop.rs
Labels: B-Substrate <> Substrate

#1157 Fix/ignore clippy warnings
  .gitlab-ci.yml
  bin/rialto-parachain/node/src/cli.rs
  bin/rialto-parachain/node/src/command.rs
  bin/rialto-parachain/node/src/service.rs
  bin/rialto-parachain/runtime/src/lib.rs
  bin/rialto/node/src/overseer.rs
  bin/rialto/node/src/service.rs
  modules/ethereum/src/lib.rs
  modules/token-swap/src/lib.rs
  primitives/chain-kusama/src/lib.rs
  primitives/ethereum-poa/src/lib.rs
  primitives/runtime/src/lib.rs
  relays/bin-substrate/src/cli/swap_tokens.rs
  relays/headers/src/headers.rs
Labels: A-chores

#1166 Publish docker images when tag of specific format(e.g. v2021-09-27, v2021-09-27-1) is pushed
  .gitlab-ci.yml
Labels: A-chores
