Repository paritytech/parity-bridges-common, pull requests merged in 2021-08, with the labels that each got.

#944 Token-swap-over-bridge pallet
  Cargo.lock
  modules/token-swap/Cargo.toml
  modules/token-swap/src/lib.rs
  modules/token-swap/src/mock.rs
  primitives/messages/src/source_chain.rs
  primitives/token-swap/Cargo.toml
  primitives/token-swap/src/lib.rs
Labels: B-Substrate <> Substrate

#1086 Make CI happy again
  .config/lingua.dic
  .gitlab-ci.yml
  bin/millau/node/src/cli.rs
  bin/rialto/node/src/cli.rs
  modules/ethereum/src/lib.rs
  modules/grandpa/src/lib.rs
  modules/token-swap/src/lib.rs
  relays/bin-ethereum/src/rpc_errors.rs
Labels: P-Devops

#1089 Migrate dispatch pallet to frame v2
  bin/millau/runtime/src/rialto_messages.rs
  bin/rialto/runtime/src/millau_messages.rs
  bin/runtime-common/src/messages.rs
  modules/dispatch/src/lib.rs
Labels: A-chores

#1091 Migrate eth PoA pallet to frame v2
  bin/rialto/runtime/src/exchange.rs
  bin/rialto/runtime/src/lib.rs
  modules/ethereum/src/benchmarking.rs
  modules/ethereum/src/finality.rs
  modules/ethereum/src/import.rs
  modules/ethereum/src/lib.rs
  modules/ethereum/src/mock.rs
  modules/ethereum/src/test_utils.rs
  modules/ethereum/src/validators.rs
  modules/ethereum/src/verification.rs
Labels: A-chores

#1090 Migrate pallet-shift-session-manager to frame v2
  modules/shift-session-manager/src/lib.rs
Labels: A-chores

#1095 Add missing docs
  .gitignore
  relays/lib-substrate-relay/src/finality_pipeline.rs
  relays/lib-substrate-relay/src/messages_lane.rs
  relays/lib-substrate-relay/src/messages_source.rs
Labels: A-chores

#1097 Upgrade currency exchange pallet to frame v2
  modules/currency-exchange/src/benchmarking.rs
  modules/currency-exchange/src/lib.rs
Labels: A-chores
