Repository paritytech/parity-bridges-common, pull requests merged in 2022-05, with the labels that each got.

#1381 Update Substrate/Polkadot refs for latest BEEFY + xcm-v3 capability
  Cargo.lock
  Cargo.toml
  bin/millau/node/src/service.rs
  deployments/networks/dashboard/grafana/beefy-dashboard.json
Labels: A-chores

#1383 Fix daily gitlab build
  .gitlab-ci.yml
Labels: A-chores

#1384 Fix for "`/root` is not writable." during deployments startup
  deployments/monitoring/GrafanaMatrix.Dockerfile
Labels: A-chores

#1385 re-enable BEEFY alarms for Rialto
  deployments/networks/dashboard/grafana/beefy-dashboard.json
Labels: A-chores, P-Devops

#1386 Fix copypaste error
  deployments/monitoring/GrafanaMatrix.Dockerfile
Labels: A-bug

#1388 Generalize error text
  relays/bin-substrate/src/main.rs
Labels: A-chores

#1379 Xcm in Rialto<>Millau bridge
  .config/lingua.dic
  Cargo.lock
  bin/millau/node/src/chain_spec.rs
  bin/millau/runtime/Cargo.toml
  bin/millau/runtime/src/lib.rs
  bin/millau/runtime/src/rialto_messages.rs
  bin/millau/runtime/src/xcm_config.rs
  bin/rialto/node/src/chain_spec.rs
  bin/rialto/runtime/Cargo.toml
  bin/rialto/runtime/src/lib.rs
  bin/rialto/runtime/src/millau_messages.rs
  bin/rialto/runtime/src/xcm_config.rs
  bin/runtime-common/Cargo.toml
  bin/runtime-common/src/integrity.rs
  bin/runtime-common/src/messages.rs
  bin/runtime-common/src/messages_api.rs
  deployments/bridges/rialto-millau/entrypoints/relay-messages-to-millau-generator-entrypoint.sh
  deployments/bridges/rialto-millau/entrypoints/relay-messages-to-rialto-generator-entrypoint.sh
  modules/messages/src/instant_payments.rs
  modules/messages/src/lib.rs
  modules/messages/src/mock.rs
  primitives/messages/src/source_chain.rs
  primitives/messages/src/target_chain.rs
Labels: P-Message Delivery, P-Message Dispatch

#1352 CheckBridgedBlockNumber signed extension to reject duplicate header-submit transactions
  Cargo.lock
  bin/millau/runtime/src/lib.rs
  deployments/bridges/westend-millau/docker-compose.yml
  deployments/bridges/westend-millau/entrypoints/relay-headers-westend-to-millau-entrypoint.sh
  modules/grandpa/src/extension.rs
  modules/grandpa/src/lib.rs
  modules/grandpa/src/mock.rs
  relays/client-millau/Cargo.toml
  relays/client-millau/src/lib.rs
Labels: P-Runtime, PR-audit-needed

#1218 Rialto parachain <> Millau messages bridge
  .config/lingua.dic
  Cargo.lock
  bin/millau/node/src/chain_spec.rs
  bin/millau/runtime/Cargo.toml
  bin/millau/runtime/src/lib.rs
  bin/millau/runtime/src/rialto_parachain_messages.rs
  bin/rialto-parachain/node/Cargo.toml
  bin/rialto-parachain/node/src/chain_spec.rs
  bin/rialto-parachain/runtime/Cargo.toml
  bin/rialto-parachain/runtime/src/lib.rs
  bin/rialto-parachain/runtime/src/millau_messages.rs
  bin/rialto/runtime/src/lib.rs
  bin/runtime-common/Cargo.toml
  bin/runtime-common/src/messages.rs
  modules/parachains/src/lib.rs
  primitives/chain-millau/src/lib.rs
  primitives/chain-rialto-parachain/src/lib.rs
  primitives/chain-rialto/src/lib.rs
  primitives/polkadot-core/src/parachains.rs
  primitives/runtime/src/lib.rs
  relays/bin-substrate/Cargo.toml
  relays/bin-substrate/src/chains/millau_headers_to_rialto_parachain.rs
  relays/bin-substrate/src/chains/millau_messages_to_rialto_parachain.rs
  relays/bin-substrate/src/chains/mod.rs
  relays/bin-substrate/src/chains/rialto_parachain.rs
  relays/bin-substrate/src/chains/rialto_parachain_messages_to_millau.rs
  relays/bin-substrate/src/chains/rialto_parachains_to_millau.rs
  relays/bin-substrate/src/cli/bridge.rs
  relays/bin-substrate/src/cli/init_bridge.rs
  relays/bin-substrate/src/cli/relay_headers.rs
  relays/bin-substrate/src/cli/relay_headers_and_messages.rs
  relays/bin-substrate/src/cli/relay_parachains.rs
  relays/client-rialto-parachain/Cargo.toml
  relays/client-rialto-parachain/src/lib.rs
  relays/parachains/src/parachains_loop.rs
Labels: P-Relay, P-Runtime

#1414 allow(clippy::too_many_arguments) for on-demand relays startup
  relays/bin-substrate/src/cli/relay_headers_and_messages.rs
Labels: A-chores, P-Relay

#1418 Fix XCM instruction weight in RialtoParachain to match Millau weight
  bin/rialto-parachain/runtime/src/lib.rs
Labels: A-chores

#1420 Remove excess verbosity from the spellcheck
  .gitlab-ci.yml
Labels: P-Devops

#1419 Fixed sparse parachains finality handling in on-demand parachains relay
  relays/lib-substrate-relay/src/on_demand/parachains.rs
  relays/lib-substrate-relay/src/parachains/source.rs
  relays/parachains/src/parachains_loop.rs
Labels: P-Relay

#1412 Add RialtoParachain <> Millau bridge to test deployments
  deployments/bridges/rialto-millau/dashboard/grafana/relay-millau-to-rialto-messages-dashboard.json
  deployments/bridges/rialto-parachain-millau/dashboard/grafana/relay-millau-to-rialto-parachain-messages-dashboard.json
  deployments/bridges/rialto-parachain-millau/dashboard/grafana/relay-rialto-parachain-to-millau-messages-dashboard.json
  deployments/bridges/rialto-parachain-millau/dashboard/prometheus/targets.yml
  deployments/bridges/rialto-parachain-millau/docker-compose.yml
  deployments/bridges/rialto-parachain-millau/entrypoints/relay-messages-to-millau-generator-entrypoint.sh
  deployments/bridges/rialto-parachain-millau/entrypoints/relay-messages-to-rialto-parachain-generator-entrypoint.sh
  deployments/bridges/rialto-parachain-millau/entrypoints/relay-millau-rialto-parachain-entrypoint.sh
  deployments/run.sh
  relays/client-substrate/src/client.rs
  relays/lib-substrate-relay/src/on_demand/headers.rs
  relays/lib-substrate-relay/src/on_demand/parachains.rs
  relays/parachains/src/parachains_loop.rs
  scripts/dump-logs.sh
Labels: A-chores

#1425 Tune alerts for parachains bridge
  deployments/bridges/rialto-millau/dashboard/grafana/relay-millau-to-rialto-messages-dashboard.json
  deployments/bridges/rialto-millau/dashboard/grafana/relay-rialto-to-millau-messages-dashboard.json
  deployments/bridges/rialto-parachain-millau/dashboard/grafana/relay-millau-to-rialto-parachain-messages-dashboard.json
  deployments/bridges/rialto-parachain-millau/dashboard/grafana/relay-rialto-parachain-to-millau-messages-dashboard.json
Labels: A-chores
