Repository paritytech/parity-bridges-common, pull requests merged in 2022-03, with the labels that each got.

#1331 Reinitialize bridge relay subcommand
  Cargo.lock
  relays/bin-substrate/Cargo.toml
  relays/bin-substrate/src/cli/mod.rs
  relays/bin-substrate/src/cli/reinit_bridge.rs
  relays/client-kusama/src/runtime.rs
  relays/client-polkadot/src/runtime.rs
  relays/lib-substrate-relay/src/finality_pipeline.rs
  relays/lib-substrate-relay/src/finality_target.rs
Labels: P-Relay

#1332 Fix clippy issues
  primitives/chain-rococo/src/lib.rs
  primitives/chain-wococo/src/lib.rs
  primitives/polkadot-core/src/lib.rs
  relays/bin-substrate/src/cli/reinit_bridge.rs
  relays/bin-substrate/src/cli/send_message.rs
  relays/lib-substrate-relay/src/helpers.rs
  relays/lib-substrate-relay/src/messages_source.rs
Labels: A-chores

#1261 Override conversion rate when computing message fee
  deployments/bridges/rialto-millau/entrypoints/relay-messages-to-millau-generator-entrypoint.sh
  deployments/bridges/rialto-millau/entrypoints/relay-messages-to-rialto-generator-entrypoint.sh
  deployments/bridges/rialto-millau/entrypoints/relay-token-swap-generator-entrypoint.sh
  relays/bin-substrate/src/cli/estimate_fee.rs
  relays/bin-substrate/src/cli/send_message.rs
  relays/bin-substrate/src/cli/swap_tokens.rs
  relays/lib-substrate-relay/src/helpers.rs
Labels: P-Relay

#1334 Fix typo in generator script
  deployments/bridges/rialto-millau/entrypoints/relay-messages-to-rialto-generator-entrypoint.sh
Labels: A-chores

#1335 Override conversion rate in tokens swap generator
  deployments/bridges/rialto-millau/entrypoints/relay-token-swap-generator-entrypoint.sh
Labels: A-chores

#1336 Fix conversion rate override in token swap
  relays/bin-substrate/src/cli/swap_tokens.rs
Labels: P-Relay

#1337 Synchronize relay cli changes and token swap generator script
  deployments/bridges/rialto-millau/entrypoints/relay-token-swap-generator-entrypoint.sh
Labels: A-chores

#1338 Fixed mess with conversion rates
  relays/bin-substrate/src/cli/estimate_fee.rs
  relays/bin-substrate/src/cli/relay_headers_and_messages.rs
  relays/lib-substrate-relay/src/conversion_rate_update.rs
  relays/lib-substrate-relay/src/helpers.rs
  relays/lib-substrate-relay/src/messages_metrics.rs
Labels: P-Relay

#1339 Fix generator scripts to be consistent with updatedrelay output
  deployments/bridges/rialto-millau/entrypoints/relay-messages-to-millau-generator-entrypoint.sh
  deployments/bridges/rialto-millau/entrypoints/relay-messages-to-rialto-generator-entrypoint.sh
Labels: A-chores

#1340 Increase rate from metric when estimating fee
  relays/bin-substrate/src/cli/estimate_fee.rs
  relays/bin-substrate/src/cli/relay_headers_and_messages.rs
  relays/bin-substrate/src/cli/send_message.rs
  relays/bin-substrate/src/cli/swap_tokens.rs
  scripts/dump-logs.sh
Labels: P-Relay, P-Message Delivery

#1341 Fix conversion rate metric in dashboards
  deployments/bridges/rialto-millau/dashboard/grafana/rialto-millau-maintenance-dashboard.json
Labels: A-chores

#1342 Get rid of '[No Data] Messages from Millau to Rialto are not being delivered' warnings
  deployments/bridges/rialto-millau/dashboard/grafana/relay-millau-to-rialto-messages-dashboard.json
  deployments/bridges/rialto-millau/dashboard/grafana/relay-rialto-to-millau-messages-dashboard.json
Labels: A-chores

#1344 Use DecodeLimit when decoding incoming calls
  Cargo.lock
  bin/runtime-common/Cargo.toml
  bin/runtime-common/src/messages.rs
Labels: P-Message Dispatch

#1345 Update regex to 1.5.5
  Cargo.lock
Labels: A-chores

#1346 Update rust edition to 2021
  bin/millau/node/Cargo.toml
  bin/millau/runtime/Cargo.toml
  bin/rialto-parachain/node/Cargo.toml
  bin/rialto-parachain/runtime/Cargo.toml
  bin/rialto/node/Cargo.toml
  bin/rialto/runtime/Cargo.toml
  bin/runtime-common/Cargo.toml
  fuzz/storage-proof/Cargo.toml
  modules/dispatch/Cargo.toml
  modules/grandpa/Cargo.toml
  modules/messages/Cargo.toml
  modules/shift-session-manager/Cargo.toml
  modules/token-swap/Cargo.toml
  primitives/chain-kusama/Cargo.toml
  primitives/chain-millau/Cargo.toml
  primitives/chain-polkadot/Cargo.toml
  primitives/chain-rialto-parachain/Cargo.toml
  primitives/chain-rialto/Cargo.toml
  primitives/chain-rococo/Cargo.toml
  primitives/chain-westend/Cargo.toml
  primitives/chain-wococo/Cargo.toml
  primitives/header-chain/Cargo.toml
  primitives/message-dispatch/Cargo.toml
  primitives/messages/Cargo.toml
  primitives/polkadot-core/Cargo.toml
  primitives/runtime/Cargo.toml
  primitives/test-utils/Cargo.toml
  primitives/token-swap/Cargo.toml
  relays/bin-substrate/Cargo.toml
  relays/client-kusama/Cargo.toml
  relays/client-millau/Cargo.toml
  relays/client-polkadot/Cargo.toml
  relays/client-rialto-parachain/Cargo.toml
  relays/client-rialto/Cargo.toml
  relays/client-rococo/Cargo.toml
  relays/client-substrate/Cargo.toml
  relays/client-westend/Cargo.toml
  relays/client-wococo/Cargo.toml
  relays/finality/Cargo.toml
  relays/lib-substrate-relay/Cargo.toml
  relays/messages/Cargo.toml
  relays/utils/Cargo.toml
Labels: A-chores

#1257 Mortal conversion rate updater transactions
  relays/bin-substrate/src/chains/kusama_messages_to_polkadot.rs
  relays/bin-substrate/src/chains/millau_messages_to_rialto.rs
  relays/bin-substrate/src/chains/polkadot_messages_to_kusama.rs
  relays/bin-substrate/src/chains/rialto_messages_to_millau.rs
  relays/bin-substrate/src/chains/rococo_messages_to_wococo.rs
  relays/bin-substrate/src/chains/wococo_messages_to_rococo.rs
  relays/bin-substrate/src/cli/relay_headers_and_messages.rs
  relays/lib-substrate-relay/src/conversion_rate_update.rs
  relays/lib-substrate-relay/src/messages_lane.rs
Labels: P-Relay

#1347 Added alerts for relay balances
  deployments/bridges/rialto-millau/dashboard/grafana/rialto-millau-maintenance-dashboard.json
Labels: A-chores

#1348 Replace From<>InboundLaneApi with direct storage reads
  bin/millau/runtime/src/lib.rs
  bin/rialto/runtime/src/lib.rs
  modules/messages/src/lib.rs
  primitives/chain-kusama/src/lib.rs
  primitives/chain-millau/src/lib.rs
  primitives/chain-polkadot/src/lib.rs
  primitives/chain-rialto/src/lib.rs
  primitives/chain-rococo/src/lib.rs
  primitives/chain-wococo/src/lib.rs
  relays/client-kusama/src/lib.rs
  relays/client-millau/src/lib.rs
  relays/client-polkadot/src/lib.rs
  relays/client-rialto/src/lib.rs
  relays/client-rococo/src/lib.rs
  relays/client-substrate/src/chain.rs
  relays/client-wococo/src/lib.rs
  relays/lib-substrate-relay/src/messages_target.rs
Labels: P-Relay, P-Runtime, P-Message Delivery

#1351 Ignore more "increase" alerts that are sometimes signalling NoData at startup
  deployments/bridges/rialto-millau/dashboard/grafana/relay-millau-to-rialto-messages-dashboard.json
  deployments/bridges/rialto-millau/dashboard/grafana/relay-rialto-to-millau-messages-dashboard.json
Labels: A-chores

#962 Support dedicated lanes for pallets
  bin/millau/runtime/src/lib.rs
  bin/millau/runtime/src/rialto_messages.rs
  bin/rialto/runtime/src/lib.rs
  bin/rialto/runtime/src/millau_messages.rs
  bin/runtime-common/Cargo.toml
  bin/runtime-common/README.md
  bin/runtime-common/src/messages.rs
  modules/messages/src/instant_payments.rs
  modules/messages/src/lib.rs
  modules/messages/src/mock.rs
  modules/token-swap/src/benchmarking.rs
  modules/token-swap/src/lib.rs
  modules/token-swap/src/mock.rs
  primitives/messages/Cargo.toml
  primitives/messages/src/source_chain.rs
Labels: P-Message Delivery, PR-audited, PR-onice

#1358 Update chain versions
  primitives/chain-kusama/src/lib.rs
  primitives/chain-polkadot/src/lib.rs
  primitives/chain-rococo/src/lib.rs
Labels: A-chores

#1359 Update parity-scale-codec to 3.1.2
  Cargo.lock
Labels: dependencies

#1360 Fix parse_transaction on Rialto+Millau
  primitives/runtime/src/chain.rs
  relays/client-millau/src/lib.rs
  relays/client-rialto/src/lib.rs
  relays/client-substrate/src/chain.rs
Labels: P-Relay

#1362 Few typos and clippy fixes
  bin/runtime-common/src/messages.rs
  modules/grandpa/src/lib.rs
  modules/messages/src/mock.rs
  modules/messages/src/outbound_lane.rs
  primitives/header-chain/src/justification.rs
  primitives/messages/src/lib.rs
  primitives/runtime/src/chain.rs
  relays/bin-substrate/src/cli/reinit_bridge.rs
  relays/lib-substrate-relay/src/conversion_rate_update.rs
  relays/lib-substrate-relay/src/messages_target.rs
Labels: A-chores

#1364 Update Substrate/Polkadot/Cumulus references
  Cargo.lock
  bin/millau/node/Cargo.toml
  bin/millau/node/src/command.rs
  bin/rialto-parachain/node/src/command.rs
  bin/rialto/node/Cargo.toml
  bin/rialto/node/src/command.rs
  relays/bin-substrate/src/cli/relay_headers_and_messages.rs
  relays/bin-substrate/src/cli/swap_tokens.rs
  relays/client-substrate/src/chain.rs
  relays/utils/src/metrics.rs
  relays/utils/src/relay_loop.rs
Labels: A-chores
