Repository paritytech/parity-bridges-common, pull requests merged in 2022-06, with the labels that each got.

#1430 Get dispatch weight from the target chain (when DispatchFeePayment::AtTargetChain is used)
  bin/millau/runtime/src/lib.rs
  bin/millau/runtime/src/xcm_config.rs
  bin/rialto-parachain/runtime/src/lib.rs
  bin/rialto/runtime/src/lib.rs
  bin/rialto/runtime/src/xcm_config.rs
  bin/runtime-common/src/messages_api.rs
  modules/messages/src/lib.rs
  primitives/chain-kusama/src/lib.rs
  primitives/chain-millau/src/lib.rs
  primitives/chain-polkadot/src/lib.rs
  primitives/chain-rialto-parachain/src/lib.rs
  primitives/chain-rialto/src/lib.rs
  primitives/chain-rococo/src/lib.rs
  primitives/chain-wococo/src/lib.rs
  primitives/messages/src/lib.rs
  primitives/messages/src/target_chain.rs
  relays/client-kusama/src/lib.rs
  relays/client-millau/src/lib.rs
  relays/client-polkadot/src/lib.rs
  relays/client-rialto-parachain/src/lib.rs
  relays/client-rialto/src/lib.rs
  relays/client-rococo/src/lib.rs
  relays/client-substrate/src/chain.rs
  relays/client-wococo/src/lib.rs
  relays/lib-substrate-relay/src/messages_source.rs
Labels: P-Message Delivery

#1435 Added one more test to the parachains finality pallet
  modules/parachains/src/lib.rs
Labels: P-Runtime

#1447 Fix clippy errors
  primitives/messages/src/storage_keys.rs
Labels: A-chores

#1448 Fix another clippy warning
  relays/bin-substrate/src/cli/reinit_bridge.rs
Labels: A-chores

#1446 Signed extension for rejecting obsolete messages pallet transactions
  Cargo.lock
  bin/millau/runtime/src/lib.rs
  bin/runtime-common/Cargo.toml
  bin/runtime-common/src/lib.rs
  bin/runtime-common/src/messages.rs
  bin/runtime-common/src/messages_extension.rs
  modules/messages/src/benchmarking.rs
  modules/messages/src/lib.rs
  primitives/messages/src/lib.rs
  relays/client-millau/src/lib.rs
  relays/lib-substrate-relay/src/messages_source.rs
  relays/lib-substrate-relay/src/messages_target.rs
  relays/messages/src/message_lane_loop.rs
  relays/messages/src/message_race_delivery.rs
Labels: P-Runtime, P-Message Delivery, PR-audit-needed, PR-breaksrelay, PR-breaksruntime

#1450 Try to fix nonces collisions when both Rialto<>Millau and RialtoParachain<>Millau bridges are running
  deployments/README.md
  deployments/bridges/rialto-parachain-millau/entrypoints/relay-messages-to-millau-generator-entrypoint.sh
  deployments/bridges/rialto-parachain-millau/entrypoints/relay-messages-to-rialto-parachain-generator-entrypoint.sh
  deployments/bridges/rialto-parachain-millau/entrypoints/relay-millau-rialto-parachain-entrypoint.sh
Labels: A-chores

#1451 Revert "try to fix nonces collisions (#1450)"
  deployments/README.md
  deployments/bridges/rialto-parachain-millau/entrypoints/relay-messages-to-millau-generator-entrypoint.sh
  deployments/bridges/rialto-parachain-millau/entrypoints/relay-messages-to-rialto-parachain-generator-entrypoint.sh
  deployments/bridges/rialto-parachain-millau/entrypoints/relay-millau-rialto-parachain-entrypoint.sh
Labels: A-chores

#1452 Fix deployments again
  bin/rialto-parachain/node/src/chain_spec.rs
Labels: A-chores

#1454 Add missing parts to rialto parachain bridge (part 1)
  bin/rialto-parachain/node/src/chain_spec.rs
  bin/rialto-parachain/runtime/src/lib.rs
  deployments/bridges/rialto-parachain-millau/entrypoints/relay-millau-rialto-parachain-entrypoint.sh
  primitives/chain-millau/src/lib.rs
  primitives/chain-rialto-parachain/src/lib.rs
  relays/bin-substrate/src/chains/millau_messages_to_rialto_parachain.rs
  relays/bin-substrate/src/chains/rialto_parachain_messages_to_millau.rs
  relays/client-rialto-parachain/src/lib.rs
Labels: A-chores

#1455 Generate large + a lot of messages in RialtoParachain <> Millau bridge
  deployments/bridges/rialto-millau/entrypoints/relay-messages-to-millau-generator-entrypoint.sh
  deployments/bridges/rialto-millau/entrypoints/relay-messages-to-rialto-generator-entrypoint.sh
  deployments/bridges/rialto-parachain-millau/entrypoints/relay-messages-to-millau-generator-entrypoint.sh
  deployments/bridges/rialto-parachain-millau/entrypoints/relay-messages-to-rialto-parachain-generator-entrypoint.sh
Labels: A-chores

#1456 Actually use RialtoParachainMessagesToMillauUpdateConversionRateCallBuilder
  relays/bin-substrate/src/chains/rialto_parachain_messages_to_millau.rs
Labels: A-chores

#1457 Fix container name in dump-logs.sh
  scripts/dump-logs.sh
Labels: A-chores

#1460 Use Millau //Iden for RialtoParachain -> Millau transactions
  bin/millau/node/src/chain_spec.rs
  deployments/README.md
  deployments/bridges/rialto-parachain-millau/entrypoints/relay-millau-rialto-parachain-entrypoint.sh
Labels: A-chores

#1461 Try to generate less invalid XCM messages
  deployments/bridges/rialto-millau/entrypoints/relay-messages-to-millau-generator-entrypoint.sh
  deployments/bridges/rialto-millau/entrypoints/relay-messages-to-rialto-generator-entrypoint.sh
Labels: A-bug

#1465 Separate signers for different complex relay layers
  bin/millau/node/src/chain_spec.rs
  deployments/bridges/rialto-millau/dashboard/grafana/rialto-millau-maintenance-dashboard.json
  deployments/bridges/rialto-parachain-millau/entrypoints/relay-millau-rialto-parachain-entrypoint.sh
  relays/bin-substrate/src/cli/mod.rs
  relays/bin-substrate/src/cli/relay_headers_and_messages.rs
  relays/lib-substrate-relay/src/lib.rs
  relays/lib-substrate-relay/src/messages_metrics.rs
Labels: P-Relay

#1470 Remove local images refs
  Dockerfile
  README.md
  deployments/bridges/rialto-millau/docker-compose.yml
  deployments/bridges/rialto-parachain-millau/docker-compose.yml
  deployments/bridges/westend-millau/docker-compose.yml
  deployments/networks/millau.yml
  deployments/networks/rialto-parachain.yml
  deployments/networks/rialto.yml
Labels: A-chores

#1471 Increase reward confirmation interval (alerts)
  deployments/bridges/rialto-millau/dashboard/grafana/relay-millau-to-rialto-messages-dashboard.json
  deployments/bridges/rialto-millau/dashboard/grafana/relay-rialto-to-millau-messages-dashboard.json
  deployments/bridges/rialto-parachain-millau/dashboard/grafana/relay-millau-to-rialto-parachain-messages-dashboard.json
  deployments/bridges/rialto-parachain-millau/dashboard/grafana/relay-rialto-parachain-to-millau-messages-dashboard.json
Labels: A-chores

#1472 Remove several false NoData alerts
  deployments/bridges/rialto-millau/dashboard/grafana/relay-millau-to-rialto-messages-dashboard.json
  deployments/bridges/rialto-millau/dashboard/grafana/relay-rialto-to-millau-messages-dashboard.json
  deployments/bridges/rialto-millau/dashboard/grafana/rialto-millau-maintenance-dashboard.json
  deployments/bridges/rialto-parachain-millau/dashboard/grafana/relay-millau-to-rialto-parachain-messages-dashboard.json
  deployments/bridges/rialto-parachain-millau/dashboard/grafana/relay-rialto-parachain-to-millau-messages-dashboard.json
  deployments/bridges/rialto-parachain-millau/dashboard/grafana/rialto-parachain-millau-maintenance-dashboard.json
Labels: A-chores

#1473 Messages are not detected by relay: increase interval from 5m to 20m
  deployments/bridges/rialto-millau/dashboard/grafana/relay-millau-to-rialto-messages-dashboard.json
  deployments/bridges/rialto-millau/dashboard/grafana/relay-rialto-to-millau-messages-dashboard.json
  deployments/bridges/rialto-parachain-millau/dashboard/grafana/relay-millau-to-rialto-parachain-messages-dashboard.json
  deployments/bridges/rialto-parachain-millau/dashboard/grafana/relay-rialto-parachain-to-millau-messages-dashboard.json
Labels: A-chores

#1475 Store both block number and hash in best finalized storage value
  modules/grandpa/src/benchmarking.rs
  modules/grandpa/src/extension.rs
  modules/grandpa/src/lib.rs
  primitives/header-chain/src/storage_keys.rs
  relays/lib-substrate-relay/src/finality/engine.rs
Labels: P-Runtime, PR-breaksruntime

#1483 Unify the operating mode for bridge pallets
  Cargo.lock
  modules/grandpa/src/benchmarking.rs
  modules/grandpa/src/lib.rs
  modules/messages/src/lib.rs
  modules/parachains/src/lib.rs
  primitives/header-chain/src/lib.rs
  primitives/header-chain/src/storage_keys.rs
  primitives/messages/src/lib.rs
  primitives/runtime/Cargo.toml
  primitives/runtime/src/lib.rs
  relays/lib-substrate-relay/src/finality/engine.rs
  relays/lib-substrate-relay/src/messages_source.rs
Labels: PR-breaksrelay, PR-breaksruntime

#1484 Parachain loop metrics
  modules/parachains/src/lib.rs
  primitives/parachains/src/lib.rs
  primitives/runtime/src/lib.rs
  relays/lib-substrate-relay/src/parachains/source.rs
  relays/lib-substrate-relay/src/parachains/target.rs
  relays/parachains/src/parachains_loop.rs
  relays/parachains/src/parachains_loop_metrics.rs
Labels: P-Relay

#1485 Increase interval for "too many unconfirmed messages" alert from 5m to 20m
  deployments/bridges/rialto-millau/dashboard/grafana/relay-millau-to-rialto-messages-dashboard.json
  deployments/bridges/rialto-millau/dashboard/grafana/relay-rialto-to-millau-messages-dashboard.json
  deployments/bridges/rialto-parachain-millau/dashboard/grafana/relay-millau-to-rialto-parachain-messages-dashboard.json
  deployments/bridges/rialto-parachain-millau/dashboard/grafana/relay-rialto-parachain-to-millau-messages-dashboard.json
Labels: A-chores
