Repository paritytech/parity-bridges-common, pull requests merged in 2023-04, with the labels that each got.

#2018 Fail with InsufficientDispatchWeight if dispatch_weight doesn't cover the weight of all bundled messages
  modules/grandpa/src/lib.rs
  modules/messages/src/lib.rs
  modules/parachains/src/lib.rs
  primitives/messages/src/lib.rs
  relays/client-rialto-parachain/src/codegen_runtime.rs
Labels: P-Runtime, PR-audit-needed

#2019 Only refund relayer if all bundled messages have been delivered/confirmed
  bin/runtime-common/src/messages_call_ext.rs
  bin/runtime-common/src/refund_relayer_extension.rs
Labels: P-Runtime, PR-audit-needed

#2002 Relay node down alert
  deployments/bridges/rococo-wococo/dashboard/grafana/bridges-alerts.json
  deployments/bridges/rococo-wococo/dashboard/grafana/rococo-wococo-maintenance-dashboard.json
Labels: A-chores

#2027 Reintroduce msg dispatch status reporting
  Cargo.lock
  bin/millau/runtime/src/xcm_config.rs
  bin/rialto-parachain/runtime/src/lib.rs
  bin/rialto/runtime/src/xcm_config.rs
  bin/runtime-common/src/integrity.rs
  bin/runtime-common/src/messages_xcm_extension.rs
  modules/messages/Cargo.toml
  modules/messages/src/benchmarking.rs
  modules/messages/src/inbound_lane.rs
  modules/messages/src/lib.rs
  modules/messages/src/mock.rs
  modules/messages/src/outbound_lane.rs
  primitives/messages/Cargo.toml
  primitives/messages/src/lib.rs
  primitives/messages/src/target_chain.rs
  primitives/runtime/src/messages.rs
Labels: P-Runtime, PR-audit-needed

#2021 Reject delivery transactions with at least one obsolete message
  bin/runtime-common/src/messages_call_ext.rs
  bin/runtime-common/src/mock.rs
  bin/runtime-common/src/refund_relayer_extension.rs
  modules/messages/src/lib.rs
Labels: P-Runtime, PR-audit-needed

#2023 Boost message delivery transaction priority
  Cargo.lock
  bin/millau/runtime/Cargo.toml
  bin/millau/runtime/src/lib.rs
  bin/millau/runtime/src/rialto_parachain_messages.rs
  bin/runtime-common/Cargo.toml
  bin/runtime-common/src/lib.rs
  bin/runtime-common/src/messages_call_ext.rs
  bin/runtime-common/src/mock.rs
  bin/runtime-common/src/priority_calculator.rs
  bin/runtime-common/src/refund_relayer_extension.rs
Labels: P-Runtime, PR-audit-needed

#2031 Refund extra weight in receive_messages_delivery_proof call
  modules/messages/src/lib.rs
  modules/messages/src/mock.rs
  modules/relayers/src/payment_adapter.rs
  primitives/messages/src/source_chain.rs
Labels: P-Runtime, PR-audit-needed

#2034 Fix build step on CI
  .gitlab-ci.yml
Labels: A-chores

#2036 Impl review suggestions from #2021
  bin/runtime-common/src/messages_call_ext.rs
  bin/runtime-common/src/refund_relayer_extension.rs
Labels: A-chores

#2041 Update refs
  Cargo.lock
  bin/millau/node/src/service.rs
  bin/rialto-parachain/node/src/service.rs
  bin/rialto/node/src/command.rs
  modules/beefy/src/lib.rs
  primitives/messages/src/lib.rs
Labels: dependencies

#2048 Revert dispatch-results
  Cargo.lock
  bin/millau/runtime/src/xcm_config.rs
  bin/rialto-parachain/runtime/src/lib.rs
  bin/rialto/runtime/src/xcm_config.rs
  bin/runtime-common/Cargo.toml
  bin/runtime-common/src/integrity.rs
  bin/runtime-common/src/messages_call_ext.rs
  bin/runtime-common/src/messages_xcm_extension.rs
  deployments/types-millau.json
  deployments/types-rialto.json
  deployments/types/common.json
  modules/messages/Cargo.toml
  modules/messages/src/benchmarking.rs
  modules/messages/src/inbound_lane.rs
  modules/messages/src/lib.rs
  modules/messages/src/mock.rs
  modules/messages/src/outbound_lane.rs
  primitives/messages/Cargo.toml
  primitives/messages/src/lib.rs
  primitives/messages/src/target_chain.rs
  primitives/runtime/src/messages.rs
Labels: A-chores

#2052 Fixed delivery alert rule
  deployments/bridges/rococo-wococo/dashboard/grafana/bridges-alerts.json
  deployments/bridges/rococo-wococo/dashboard/grafana/relay-rococo-to-wococo-messages-dashboard.json
  deployments/bridges/rococo-wococo/dashboard/grafana/relay-wococo-to-rococo-messages-dashboard.json
Labels: A-chores

#2030 submit lane unblock transactions from relay
  Cargo.lock
  relays/client-substrate/src/chain.rs
  relays/lib-substrate-relay/src/lib.rs
  relays/messages/Cargo.toml
  relays/messages/src/message_lane_loop.rs
  relays/messages/src/message_race_delivery.rs
  relays/messages/src/message_race_loop.rs
  relays/messages/src/message_race_strategy.rs
Labels: P-Relay

#2065 Do not select any nonces in delivery race if something is already selected/submitted
  relays/messages/src/message_race_delivery.rs
Labels: A-bug, P-Relay

#2073 Messages relay fixes
  relays/messages/src/message_race_delivery.rs
  relays/messages/src/message_race_loop.rs
  relays/messages/src/message_race_strategy.rs
Labels: A-bug, P-Relay

#2075 Fixed off-by-one when confirming rewards in messages pallet
  modules/messages/src/inbound_lane.rs
  modules/messages/src/lib.rs
  modules/messages/src/mock.rs
Labels: A-bug

#2082 Add more logs to relayer and message pallets
  modules/messages/src/lib.rs
  modules/messages/src/mock.rs
  modules/relayers/src/lib.rs
  primitives/messages/src/lib.rs
Labels: A-chores
