Repository paritytech/parity-bridges-common, pull requests merged in 2023-07, with the labels that each got.

#2227 Introduce MessagesLaneManager
  bin/runtime-common/src/mock.rs
  modules/messages/src/inbound_lane.rs
  modules/messages/src/lanes_manager.rs
  modules/messages/src/lib.rs
  modules/messages/src/outbound_lane.rs
  modules/messages/src/tests/pallet_tests.rs
  primitives/header-chain/src/lib.rs
  primitives/messages/src/lib.rs
  primitives/messages/src/target_chain.rs
Labels: P-Runtime

#2238 Ensure that the origin is signed for submit_parachain_heads and submit_finality_proof calls
  modules/grandpa/src/lib.rs
  modules/parachains/src/lib.rs
Labels: A-bug

#2239 Ensure that the origin is signed for submit_parachain_heads and submit_finality_proof calls
  modules/grandpa/src/lib.rs
  modules/parachains/src/lib.rs
Labels: A-bug

#2240 Fix clippy
  Cargo.lock
  modules/messages/src/outbound_lane.rs
Labels: A-chores

#2257 Allow delivery confirmations on closed outbound lanes
  modules/messages/src/benchmarking.rs
  modules/messages/src/inbound_lane.rs
  modules/messages/src/lib.rs
  modules/messages/src/outbound_lane.rs
  modules/messages/src/tests/pallet_tests.rs
Labels: A-chores, P-Runtime, PR-audit-needed

#2259 Remove internal code that pretends to support cross-lane delivery transactions
  modules/messages/src/lib.rs
  modules/messages/src/proofs.rs
  primitives/messages/src/target_chain.rs
Labels: P-Runtime

#2264 Backport: GRANDPA: optimize votes_ancestries when needed
  primitives/header-chain/src/justification.rs
  primitives/header-chain/tests/implementation_match.rs
  primitives/header-chain/tests/justification.rs
  relays/lib-substrate-relay/src/finality/engine.rs
  relays/lib-substrate-relay/src/finality/target.rs
  relays/lib-substrate-relay/src/on_demand/headers.rs
Labels: PR-audit-needed

#2265 Introduce partial bp-xcm-bridge-hub - just LocalXcmChannelManager
  Cargo.lock
  Cargo.toml
  primitives/xcm-bridge-hub/Cargo.toml
  primitives/xcm-bridge-hub/src/lib.rs
Labels: P-Runtime

#2276 Some code grooming
  .gitlab-ci.yml
  bin/runtime-common/src/lib.rs
  bin/runtime-common/src/messages_call_ext.rs
  bin/runtime-common/src/messages_xcm_extension.rs
  bin/runtime-common/src/parachains_benchmarking.rs
  bin/runtime-common/src/refund_relayer_extension.rs
  deny.toml
  modules/beefy/src/lib.rs
  modules/grandpa/src/lib.rs
  modules/messages/src/lib.rs
  modules/parachains/src/lib.rs
  modules/shift-session-manager/src/lib.rs
  primitives/chain-bridge-hub-cumulus/src/lib.rs
  primitives/chain-bridge-hub-kusama/src/lib.rs
  primitives/chain-bridge-hub-polkadot/src/lib.rs
  primitives/chain-bridge-hub-rococo/src/lib.rs
  primitives/chain-bridge-hub-wococo/src/lib.rs
  primitives/chain-kusama/src/lib.rs
  primitives/chain-millau/src/lib.rs
  primitives/chain-polkadot/src/lib.rs
  primitives/chain-rialto-parachain/src/lib.rs
  primitives/chain-rialto/src/lib.rs
  primitives/chain-rococo/src/lib.rs
  primitives/chain-westend/src/lib.rs
  primitives/chain-wococo/src/lib.rs
  primitives/header-chain/src/justification.rs
  primitives/header-chain/src/lib.rs
  primitives/messages/src/lib.rs
  primitives/parachains/src/lib.rs
  primitives/polkadot-core/src/lib.rs
  primitives/polkadot-core/src/parachains.rs
  primitives/runtime/src/extensions.rs
  primitives/runtime/src/lib.rs
  primitives/runtime/src/storage_proof.rs
  primitives/test-utils/src/keyring.rs
  primitives/test-utils/src/lib.rs
Labels: A-chores

#2213 XCM bridge hub pallet (will be deployed at bridge hubs)
  Cargo.lock
  Cargo.toml
  modules/xcm-bridge-hub/Cargo.toml
  modules/xcm-bridge-hub/src/lib.rs
  modules/xcm-bridge-hub/src/mock.rs
  primitives/messages/src/lib.rs
  primitives/xcm-bridge-hub/Cargo.toml
  primitives/xcm-bridge-hub/src/lib.rs
Labels: P-Runtime, PR-audit-needed

#2282 More backports from Cumulus subtree
  bin/millau/node/src/chain_spec.rs
  bin/millau/runtime/src/lib.rs
  deployments/README.md
  deployments/bridges/westend-millau/dashboard/grafana/relay-westend-to-millau-parachains-dashboard.json
  deployments/bridges/westend-millau/docker-compose.yml
  deployments/bridges/westend-millau/entrypoints/relay-parachains-westend-to-millau-entrypoint.sh
  modules/grandpa/Cargo.toml
  primitives/chain-westend/src/lib.rs
  primitives/header-chain/Cargo.toml
  primitives/parachains/Cargo.toml
  primitives/runtime/Cargo.toml
  relays/bin-substrate/src/bridges/westend_millau/westend_parachains_to_millau.rs
  relays/bin-substrate/src/chains/westend.rs
  relays/bin-substrate/src/cli/relay_parachains.rs
  relays/client-westend/src/lib.rs
Labels: A-chores

#2283 More backports from Cumulus subtree to polkadot-staging
  bin/millau/node/src/chain_spec.rs
  bin/millau/runtime/src/lib.rs
  deployments/README.md
  deployments/bridges/westend-millau/dashboard/grafana/relay-westend-to-millau-parachains-dashboard.json
  deployments/bridges/westend-millau/docker-compose.yml
  deployments/bridges/westend-millau/entrypoints/relay-parachains-westend-to-millau-entrypoint.sh
  modules/grandpa/Cargo.toml
  primitives/chain-westend/src/lib.rs
  primitives/header-chain/Cargo.toml
  primitives/parachains/Cargo.toml
  primitives/runtime/Cargo.toml
  primitives/runtime/src/lib.rs
  relays/bin-substrate/src/bridges/westend_millau/westend_parachains_to_millau.rs
  relays/bin-substrate/src/chains/westend.rs
  relays/bin-substrate/src/cli/relay_parachains.rs
  relays/client-westend/src/lib.rs
Labels: A-chores

#2285 Implement ExportXcm and MessageDispatch for pallet-xcm-bridge-hub
  modules/xcm-bridge-hub/Cargo.toml
  modules/xcm-bridge-hub/src/dispatcher.rs
  modules/xcm-bridge-hub/src/exporter.rs
  modules/xcm-bridge-hub/src/lib.rs
  modules/xcm-bridge-hub/src/mock.rs
Labels: P-Runtime, PR-audit-needed
